global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus_rules.yml"

scrape_configs:
  - job_name: 'article-search-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/monitoring/metrics'
    scrape_interval: 10s

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # Здесь можно добавить Alertmanager при необходимости